steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/gcpdevops", "."]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "-t", "gcr.io/$PROJECT_ID/gcpdevops", "."]
  - name: "gcr.io/cloud-builders/docker"
    args:
      - run
      - --filename-gke.yaml
      - --image=gcr.io/$PROJECT_ID/gcpdevops
      - --cluster=gcp-devops-project
      - --namespace=gcp-devops-project
